### PR TITLE
PREOPS-3547: if the gpu.js library fails to load, fall back on using the CPU

### PR DESCRIPTION
**Pull request by ehneilsen**

### CODE REVIEW

**Comment by rhiannonlynne** [comment]
I still find that it's failing silently. 
* checkout out this branch
* ran uranography.ipynb notebook using `jupyter notebook uranography.ipynb`
* cell looks like it runs ok but produces no output 
* 
Screenshot 2023-06-26 at 3 10 49 PM

**Comment by ehneilsen** [comment]
By "failing silently", do you mean only that there isn't on error reported in the jupyter notebook, or do you mean that there are no errors in either the notebook or your browser's javascript console? Saving (or giving a screenshot of) the javascript console would be helpful (I still can't reproduce this on my own machine).

**Comment by rhiannonlynne** [comment]
Ah, actually I meant that there was no output in the notebook window nor in my xterm window where Jupyter was running.

**Comment by rhiannonlynne** [comment]
Confirmed that this works (was potentially a pip installed older copy that was being picked up before -- when checking it was installed with `pip install -e . ` then the expected behavior happens and works.

**Review by rhiannonlynne — APPROVED** [review]

**Pull request merged**
